ALTER TABLE projects ADD COLUMN objetivo TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN estado TEXT NOT NULL DEFAULT 'activo';
ALTER TABLE projects ADD COLUMN milestones TEXT NOT NULL DEFAULT '[]';
