import { localRepo } from "./local";
import type { Repo } from "./types";

export const repo: Repo = localRepo;
export type {
  AccountCreate,
  AccountPatch,
  AccountTransferCreate,
  AccountTransferPatch,
  AutomationCreate,
  AutomationPatch,
  BudgetUpsert,
  CoffeeBeanCreate,
  CoffeeBeanPatch,
  CoffeeRecipeCreate,
  CoffeeRecipePatch,
  CategoryCreate,
  EventCreate,
  EventPatch,
  CategoryPatch,
  ExpenseCategoryCreate,
  ExpenseCategoryPatch,
  IngredientCategoryCreate,
  IngredientCategoryPatch,
  ExpenseCreate,
  ExpensePatch,
  ExpenseLineItemCreate,
  ExpenseLineItemPatch,
  HabitLogUpsert,
  IncomeUpsert,
  ProjectCreate,
  ProjectPatch,
  Repo,
  SavingsContributionUpsert,
  SavingsGoalCreate,
  SavingsGoalPatch,
  ShoppingItemCreate,
  ShoppingItemPatch,
  IngredientCreate,
  IngredientPatch,
  IngredientPresentationCreate,
  IngredientPresentationPatch,
  RecipeCreate,
  RecipePatch,
  RecipeIngredientCreate,
  RecipeIngredientPatch,
  SavedListCreate,
  SavedListPatch,
  MealPlanEntryCreate,
  MealPlanEntryPatch,
  InventoryCreate,
  InventoryPatch,
  MealLogCreate,
  ComprasSettingsUpsert,
  FinanzasSettingsUpsert,
  NetWorthSnapshotUpsert,
  TaskCreate,
  TaskPatch,
  BrewSessionCreate,
} from "./types";
